name: square_in_app_payments
description: An open source Flutter plugin for calling Square’s native In-App Payments SDK to take in-app payments on iOS and Android.
version: 1.6.0
homepage: https://github.com/square/in-app-payments-flutter-plugin
documentation: https://github.com/square/in-app-payments-flutter-plugin

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.0
  built_collection: ^4.0.0
  meta: ^1.1.6

dev_dependencies:
  build: ^1.1.0
  build_runner: ^1.2.3
  source_gen:  ^0.9.4+1
  built_value_generator: ^7.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: sqip.flutter
        pluginClass: SquareInAppPaymentsFlutterPlugin
      ios:
        pluginClass: SquareInAppPaymentsFlutterPlugin
